overrides:
  '@making-sense/antlr4ng': ^3.0.16
  monaco-editor: ^0.56.0

minimumReleaseAgeExclude:
  - electron-to-chromium
  - tinybench
  - vite

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
